### ISSUE TITLE
Bug: Error: cannot import name 'parse_form' from 'web.dependencies'

### ISSUE THREAD

**Issue by lazmodo** [StudioNirin/PlexCache-R#119]
### Description
I updated the docker container, and after restarting, I am unable to load the webUI. the script fails with a `cannot Import` error. It appears the `parse_form` function is either missing or inaccessible within the `web.dependencies` module.

### Error:
` Starting PlexCache-D Web UI...`
`----------------------------------------`
`Error: Failed to import web application: cannot import name 'parse_form' from 'web.dependencies' (/app/web/dependencies.py)`

### Additional Context

I tried a git pull on the script version I'm running, and encountered the same error when I ran `python3 plexcache.py --web`.  It looks like `python3 plexcache.py --dry-run --verbose` does run as expected so I think it's the `def parse_form` missing from `dependencies.py` preventing the UI from loading.

**Comment by BBergle** [comment]
Same issue here, reverting to the old image fixes it. `ghcr.io/studionirin/plexcache-d@sha256:50eec7a1516eba316fc00d8c86ddb0210f692337f38aa80c4f12629865c90feb`

**Comment by Brandon-Haney** [comment]
This was caused by PR #112 (maintenance bulk actions) referencing parse_form from web.dependencies, but the function definition wasn't included in that cherry-pick. Hotfix PR #120 adds the missing dependency. Sorry for the breakage

**Comment by BBergle** [comment]
Thanks for the fix!
